language: minimal

services:
  - docker


before_install:
  - python3 -m venv venv/
  - source venv/bin/activate

install:
  - pip install black isort flake8

script:
  - black --check .
  - isort --recursive --check-only --diff
  - flake8
  - ./run-tests.sh
