language: python
sudo: required
dist: xenial
python: "3.7"

services:
  - docker
  
install:
  - pip install black isort flake8

script:
  - black --check .
  - isort --recursive --check-only --diff
  - flake8
  - ./run-tests.sh
