version: '3'

volumes:
  database:
    external: false

services:
  database:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  web:
    build: .
    command: start
    entrypoint: /app/docker-entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - database:database
