# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 17:42
from __future__ import unicode_literals

import datetime

import django.utils.timezone
import pytz
from django.db import migrations, models

utc = pytz.utc


def set_created_at_defaults(apps, schema_editor):
    print("Setting user created_at defaults...")
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    users = User.objects.using(db_alias).all()
    for user in users:
        user_comments = user.comment_set.order_by("-created_at")
        if user_comments.exists():
            first_comment = user_comments.first()
            created_at = first_comment.created_at
            user.created_at = datetime.datetime.combine(
                created_at, datetime.time(tzinfo=utc)
            )

            user.save()
        else:
            user.created_at = django.utils.timezone.now()
            user.save()


def reverse_created_at_defaults(apps, schema_editor):
    pass


def set_modified_at_defaults(apps, schema_editor):
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    users = User.objects.using(db_alias).all()
    for user in users:
        user.modified_at = user.created_at
        user.save()


def reverse_modified_at_defaults(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
        # Set created_at field as the User's first comment creation date, or default if no first comment
        migrations.RunPython(set_created_at_defaults),
        # Remove null=True
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="modified at"
            ),
        ),
        # Set modified_at field as the same as the created_at field by default
        migrations.RunPython(set_modified_at_defaults),
        # Remove null=True
        migrations.AlterField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
    ]
