# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 16:52


from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=b"name", unique=True
                    ),
                ),
            ],
        )
    ]
