# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 16:53


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("professors", "0001_squashed_0002_auto_20180825_2204"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateField()),
                ("is_anonymous", models.BooleanField()),
                ("responsibility", models.IntegerField(null=True)),
                ("personality", models.IntegerField(null=True)),
                ("workload", models.IntegerField(null=True)),
                ("difficulty", models.IntegerField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.Professor",
                    ),
                ),
            ],
        )
    ]
