# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 16:53


from django.db import migrations, models

import notaso.universities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=25)),
                (
                    "emblem",
                    models.FileField(
                        upload_to=notaso.universities.models.get_upload_file_name
                    ),
                ),
                ("slug", models.SlugField()),
            ],
        )
    ]
